local _
local AddonName, ns	= ...
local L	= CreateFrame"Frame"
ns.L	= L
if (GetLocale()	== "zhCN") then
	--默认语言为简体中文
	
elseif (GetLocale()	== "zhTW") then
	L.Default = "預設"

	L.resd = "重新載入介面以恢復預設值"
	L.confirm = "確認"
	L.cancel = "取消"
	L.dtools2 = "介面美化"
	L.captext = "|cff00EE00Shift|r 按住可移動預設頭像、血量條、數據資訊等\n(調整動作條時可關閉動作條)\n|cff00EE00/di|r 快速開啟設定介面\n|cff00EE00/npd|r 恢復名條預設設定"
	L.printh2 = "|cff00EE00/rl|r 重新載入介面\n|cff00EE00/di|r 快速開啟設定介面"
	L.printh = "使用說明"

	L.aab1 = "攻擊計時器"
	L.aab2 = "武器自動攻擊計時器"
	L.acu1 = "動作條"
	L.acu2 = "動作條增強美化"
	L.acm0 = "典範"
	L.acm1 = "點擊"
	L.acm2 = "更多"
	L.acm3 = "三線"
	L.acc1 = "邊框染色"
	L.acc2 = "染色動作條按鈕邊框"
	L.acp1 = "進階美化"
	L.acp2 = "美化動作條按鈕邊框背景"
	L.acr1 = "隱藏圖示動畫"
	L.acr2 = "關閉 10.0 新增圖示施法動畫"
	L.aug1 = "自動組隊"
	L.aug2 = "密語自動組隊 (|cffFFFF00/1|r)"
	L.aur1 = "自動修理"
	L.aur2 = "自動修理裝備 (優先公會修理)"
	L.aus1 = "自動販賣"
	L.aus2 = "自動販賣灰色垃圾"
	L.aua1 = "自動擷圖"
	L.aua2 = "獲得成就時自動擷圖"
	L.bfm1 = "面板移動"
	L.bfm2 = "內建面板框架自由移動"
	L.cbb1 = "施法條增強"
	L.cbb2 = "玩家施法條增強"
	L.cbi1 = "戰鬥指示器"
	L.cbi2 = "大腳戰鬥指示器"
	L.cfp1 = "聊天增強"
	L.cfp2 = "聊天美化增強"
	L.cfbb1 = "底部按鈕"
	L.cfbb2 = "將聊天欄按鈕移至框架底部"
	L.chr1 = "聊天記錄"
	L.chr2 = "還原上次遊戲的聊天記錄"
	L.ctbr1 = "戰鬥計時器"
	L.ctbr2 = "戰鬥與戰復計時工具"
	L.fsl1 = "快速拾取"
	L.fsl2 = "拾取框架加速"
	L.glob1 = "全域設定"
	L.glob2 = "所有角色共用設定。(變更後需重新載入介面。)"
	L.hsf1 = "|cff00FF00Shift|r 設為專注目標"
	L.hsf2 = "按住 |cffFFFF00Shift|r 設為專注目標"
	L.ifs1 = "數據資訊"
	L.ifs2 = "移動速度、FPS、延遲、記憶體"
	L.ifsc1 = "彩色字型"
	L.ifsc2 = "數據字型染色"
	L.ifss1 = "大字型"
	L.ifss2 = "加大數據資訊字型"
	L.ist1 = "打斷提示"
	L.ist2 = "打斷目標施法提示"
	L.npu1 = "名條增強"
	L.npu2 = "簡易名條美化增強"
	L.otb1 = "追蹤美化"
	L.otb2 = "任務追蹤文字美化 (戰鬥中可能介面行為失效)"
	L.pnc1 = "角色改名"
	L.pnc2 = "|cff00FF00/CN/cname|r 變更本機玩家角色名稱"
	L.pnc3 = "|cff00FF00/CN|r 重新命名"
	L.ruu1 = "團隊框架美化"
	L.ruu2 = "團隊框架美化"
	L.sfu1 = "字型美化"
	L.sfu2 = "美化遊戲內大部分文字"
	L.tiu1 = "提示增強"
	L.tiu2 = "滑鼠提示美化增強"
	L.tiub1 = "放大"
	L.tiub2 = "放大提示框架"
	L.una1 = "玩家框架淡出"
	L.una2 = "戰鬥中無目標時頭像框架逐漸消失"
	L.unc1 = "職業顏色調整"
	L.unc2 = "使用明亮一組的職業顏色"
	L.unfn1 = "隱藏名字"
	L.unfn2 = "隱藏玩家名字"
	L.unft1 = "精英材質"
	L.unft2 = "金龍紋理製作的玩家框架"
	L.uns1 = "放大框架"
	L.uns2 = "更大的預設頭像框架"
	L.unu1 = "框架增強"
	L.unu2 = "預設單位框架美化增強"
	L.vap1 = "語音通報"
	L.vap2 = "標記獲得語音提示"

	L.oufd1 = "暗黑球體"
	L.oufd2 = "oUF 製作的暗黑球體玩家框架"
	L.oufc1 = "職業顏色"
	L.oufc2 = "職業顏色球體染色"
	L.dadf1 = "裝飾"
	L.dadf2 = "惡魔與天使裝飾素材"
	L.dhpg1 = "邊框"
	L.dhpg2 = "血量條周圍邊框"
	L.dpet1 = "寵物框架"
	L.dpet2 = "生命球上方的寵物框架"
	L.dduf1 = "預設框架"
	L.dduf2 = "啟用被 oUF 隱藏的預設玩家框架"
	L.uisl1 = "介面縮放鎖定"
	L.uisl2 = "開啟並鎖定介面縮放 (調整介面縮放後需重置位置)"
	L.daml1 = "動作條微調"
	L.daml2 = "自訂並鎖定部分動作條 (戰鬥中無法使用編輯模式)"

	L.bart = "狀態條材質"
	L.tipc = "滑鼠提示"
	L.tipc1 = "跟隨"
	L.tipc2 = "不跟隨"
	L.tipc3 = "非戰鬥跟隨"
	L.sqw1 = "施法延遲"
	L.sqw2 = "施法序列延遲"
	L.brtx = "版本"
	L.adrl = "重新載入"
	L.slb = "推薦"
	L.resdef = "恢復預設值"
	L.respos = "重置位置"
	L.feedback = "|cffEEFF7FQQ群 :|r974344392"
	L.print = "開啟設定介面"
	L.bloodcc = "設定"
	L.diablotip = "|cffffff00附加元件列表可完全關閉|r"

	-- 聊天
	L.say = "說"
	L.yell = "大喊"
	L.party = "隊伍"
	L.guild = "公會"
	L.raid = "團隊"
	L.instance = "副本"
	L.general1 = "綜"
	L.general2 = "綜合"
	L.general3 = "你沒有綜合頻道"
	L.trade1 = "交"
	L.trade2 = "交易"
	L.trade3 = "你不在交易頻道，請在主城加入"
	L.lookingforgroup1 = "尋"
	L.lookingforgroup2 = "尋求組隊"
	L.lookingforgroup3 = "已加入尋求組隊頻道"
	L.lookingforgroup4 = "離開尋求組隊頻道"
	L.world1 = "世"
	L.world2 = "世界"
	L.world3 = "已加入世界頻道"
	L.world4 = "離開世界頻道"
	L.rep = "聲望"
	L.eql = "裝等"
	L.class = "職業"
	L.spec = "天賦"

	-- 資訊
	L.fps = "FPS"
	L.lag = "延遲"
	L.player = "玩家"
	L.target = "目標"
	L.vehicle = "載具"
	L.none = "無"
	L.lootspec = "拾取專精"
	L.ile = "物品等級"
	L.str = "力量"
	L.agi = "敏捷"
	L.int = "智力"
	L.cri = "致命"
	L.has = "加速"
	L.mas = "精通"
	L.ver = "應變"

	L.attp = "攻擊強度"
	L.spbd = "法術能量"
	L.armp = "護甲穿透"
	L.manar = "法力恢復"
	L.armor = "護甲值"
	L.dodge = "閃躲"
	L.parry = "招架"
	L.block = "格擋"
	L.atts = "攻擊速度"

	L.clearm = "清理記憶體"
	L.total = "總計"
	L.totalb = "總計 (含暴雪)"
	L.sspec = "切換專精"
	L.nospec = "尚未專精"
	L.slspec = "切換拾取專精"

	-- 模組
	L.guildrepair = "本次使用公會修理"
	L.guildra = "剩餘公會修理可用次數"
	L.selfrepair = "自費修理"
	L.norepair = "我沒錢修理裝備。"
	L.sellg = "販賣垃圾"
	L.hidoroff = "對方隱形或無角色在線，無法邀請"
	L.cutin = "打斷 "
	L.enytc = "輸入你想變更的名稱，不輸入則恢復原名"
	L.carti = "確認並重新載入介面"
	L.chr3 = "聊天記錄"

	-- 其他
	L.buyco = "成功購買 1 件物品"
	L.buydpc = "購買失敗，價格變動"
	L.buyalp = "以最低價購買一件"
	L.untre = "無法重置"
	L.hbre = "已重置"
	L.ltteam = "離開隊伍"
	L.ftayt = "本活動你的隊伍已滿，將從列表中移除"
	L.era = "紀元"

	-- 設定插件
	L.cdscr = "DBM、Skada.. 設定已變更，重新載入介面應用變更！"
	L.setup = "設定"
	L.ritss = "重置介面儲存設定"

	-- 設定 CVar
	L.comlc = "戰鬥中禁用設定"
	L.decpt = "偵測到錯誤收集插件，關閉預設 LUA 錯誤顯示"
	L.nedtc = "未偵測到錯誤收集插件，開啟預設 LUA 錯誤顯示"
	L.on = "開啟"
	L.off = "關閉"
	L.tgcb = "目標施法條"
	L.comif = "戰鬥資訊"
	L.teaml = "團隊佈局"
	L.tprl = "20 人團隊佈局"
	L.tfprl = "25 人團隊佈局"
	L.fprl = "40 人團隊佈局"
	L.tips = "提示"
	L.itine = "如有錯誤，請重新載入介面！"
	L.reload = "重新載入介面？"
	L.uhset = "使用習慣設定"
	L.care = "注意！"
	L.nprd = "重置名條至預設值？"

	-- 滑鼠提示
	L.afk = "暫離"
	L.offl = "離線"
	L.rare = "稀有"
	L.raree = "稀有精英"
	L.elite = "精英"
	L.ghost = "靈魂"
	L.dead = "死亡"
	L.targ = "目標"
	L.you = "你"
	L.epicra = "史詩等級"
	L.dungeons = "地下城"
	L.ratle = "評級等級"
	L.item = "物品"
	L.iteml = "物品等級"
	L.spell = "法術"
	L.ppu = "單價"

elseif (GetLocale()	== "ruRU") then
	--by:ZamestoTV
	L.Default = "По умолчанию"

	L.resd	= "Перезагрузите интерфейс, чтобы восстановить настройки по умолчанию"
	L.confirm	= "Подтвердить"
	L.cancel	= "Отмена"
	L.dtools2	= "Украшение интерфейса"
	L.captext	= "|cff00EE00Shift|r - удерживайте для перемещения стандартных аватаров и т.д.\n(Настройка панели действий может отключить панель действий)\n|cff00EE00/di|r - Быстро открыть интерфейс настроек\n|cff00EE00/npd|r - Восстановить настройки индикаторов здоровья по умолчанию"
	L.printh2	= "|cff00EE00/rl|r - Перезагрузить интерфейс\n|cff00EE00/di|r - Быстро открыть интерфейс настроек"
	L.printh	= "Инструкции"

	L.aab1	= "Таймер атаки"
	L.aab2	= "Таймер автоатаки оружия"
	L.acu1	= "Панель действий"
	L.acu2	= "Улучшение и украшение панели действий"
	L.acm0	= "обычный"
	L.acm1	= "нажать"
	L.acm2	= "больше"
	L.acm3	= "Три строки"
	L.acc1	= "Черная рамка"
	L.acc2	= "Окрасить рамку кнопок панели действий"
	L.acp1	= "Продвинутое украшение"
	L.acp2	= "Украсить фон рамки кнопок панели действий"
	L.acr1	= "Скрыть аним. иконок"
	L.acr2	= "Отключить анимацию заклинаний для новых иконок в 10.0"
	L.aug1	= "Автоформирование"
	L.aug2	= "Автоматическое формирование шифротекста (|cffFFFF00/1|r)"
	L.aur1	= "Авторемонт"
	L.aur2	= "Автоматический ремонт снаряжения (приоритет у ремонта гильдии)"
	L.aus1	= "Автопродажа"
	L.aus2	= "Автоматическая продажа серого мусора"
	L.aua1	= "Автоскриншоты"
	L.aua2	= "Автоматическое создание скриншотов при получении достижений"
	L.bfm1	= "Перемещение панелей"
	L.bfm2	= "Свободное перемещение встроенных панелей"
	L.cbb1	= "КастБар+"
	L.cbb2	= "Улучшение полосы заклинаний игрока"
	L.cbi1	= "Индикатор боя"
	L.cbi2	= "Индикатор боя от Bigfoot"
	L.cfp1	= "Улучшение чата"
	L.cfp2	= "Украшение и улучшение чата"
	L.cfbb1	= "Нижняя кнопка"
	L.cfbb2	= "Перемещение кнопки чата в нижнюю часть окна"
	L.chr1	= "История чата"
	L.chr2	= "Восстановить историю чата из прошлой игры"
	L.ctbr1 = "Таймер боя"
	L.ctbr2 = "Инструмент для отслеживания боя и боевого воскрешения"
	L.fsl1	= "Быстрый сбор"
	L.fsl2	= "Ускорение окна сбора"
	L.glob1	= "Глоб. конфиг"
	L.glob2	= "Общий конфиг для всех ролей. (Требуется перезагрузка UI.)"
	L.hsf1	= "|cff00FF00Shift|rФокус"
	L.hsf2	= "Держи|cffFFFF00Shift|rНастройка фокуса"
	L.ifs1	= "Информация о данных"
	L.ifs2	= "Скорость передвижения, FPS, Задержка, Память"
	L.ifsc1 = "Цветной шрифт"
	L.ifsc2 = "Окрашивание шрифта данных"
	L.ifss1	= "Большой шрифт"
	L.ifss2	= "Увеличение размера шрифта для информации о данных"
	L.ist1	= "Прерывание закл."
	L.ist2	= "Подсказка о прерывании заклинания цели"
	L.npu1	= "Индикатор здоровья"
	L.npu2	= "Простое улучшение и украшение индикаторов здоровья"
	L.otb1	= "Отслеживание"
	L.otb2	= "Украшение текста отслеживания заданий (Возможны сбои в поведении интерфейса во время боя)"
	L.pnc1	= "Переименование персонажа"
	L.pnc2	= "|cff00FF00/CN/cname|r - Изменить имя локального персонажа"
	L.pnc3	= "|cff00FF00/CN|r Переим."
	L.ruu1	= "Окна рейда"
	L.ruu2	= "Украшение окон рейда"
	L.sfu1	= "Шрифты"
	L.sfu2	= "Украшение большей части текста в игре"
	L.tiu1	= "Подсказки"
	L.tiu2	= "Украшение и улучшение подсказок при наведении мыши"
	L.tiub1	= "Увеличить"
	L.tiub2	= "Увеличение рамки всплывающей подсказки"
	L.una1	= "Окна игрока"
	L.una2	= "Окно для постепенного исчезновения аватара без цели в бою"
	L.unc1	= "Цвет класса"
	L.unc2	= "Использовать яркий набор цветов для классов"
	L.unfn1	= "Скрыть имя"
	L.unfn2	= "Скрыть имя игрока"
	L.unft1	= "Текстура Элиты"
	L.unft2	= "Окно игрока с текстурой золотого дракона"
	L.uns1	= "Увеличить рамку"
	L.uns2	= "Большая рамка аватара по умолчанию"
	L.unu1	= "Окна"
	L.unu2	= "Улучшение и украшение стандартных окон"
	L.vap1	= "Голосовые объявления"
	L.vap2	= "Голосовая подсказка при получении метки"

	L.oufd1	= "Диабло"
	L.oufd2	= "Окно игрока Сферы Диабло от oUF"
	L.oufc1	= "Цвет класса"
	L.oufc2	= "Окрашивание сферы в цвет класса"
	L.dadf1	= "Декорация"
	L.dadf2	= "Демоны и ангелы украшают материал"
	L.dhpg1	= "Границы"
	L.dhpg2	= "Границы вокруг кровяных клеток"
	L.dpet1	= "Окно питомца"
	L.dpet2	= "Окно питомца над сферой жизни"
	L.dduf1	= "Стандартное окно"
	L.dduf2	= "Включить стандартное окно игрока, скрытый oUF"
	L.uisl1	= "Блок масштаба UI"
	L.uisl2	= "Открыть и заблокировать масштаб интерфейса (После настройки масштаба интерфейса необходимо сбросить позиции)"
	L.daml1	= "Тонкая настройка"
	L.daml2	= "Настройка и блокировка некоторых панелей действий (Режим редактирования может вызывать ошибки во время боя)"

	L.bart = "Текстура бар"
	L.tipc 	= "Подсказка"
	L.tipc1	= "Следовать"
	L.tipc2	= "Не следовать"
	L.tipc3	= "Следовать вне боя"
	L.sqw1	= "Задержка закл."
	L.sqw2	= "Задержка последовательности заклинаний"
	L.brtx	= "Версия"
	L.adrl	= "Перезагрузить"
	L.slb	= "Рекомендация"
	L.resdef	= "По умолчанию"
	L.respos	= "Сбросить"
	L.feedback	= "|cffEEFF7FQQGroup :|r974344392"
	L.print	= "Открыть интерфейс настроек"
	L.bloodcc	= "Настройка"
	L.diablotip = "|cffffff00Отключите в списке плагинов|r"

	-- Чат
	L.say	= "С"
	L.yell	= "К"
	L.party	= "Г"
	L.guild	= "Г"
	L.raid	= "Р"
	L.instance	= "П"
	L.general1	= "О"
	L.general2	= "Общий"
	L.general3	= "У вас нет общего канала"
	L.trade1	= "Т"
	L.trade2	= "Торговля"
	L.trade3	= "Вы не в торговом канале, присоединитесь в главном городе"
	L.lookingforgroup1	= "Л"
	L.lookingforgroup2	= "Поиск группы"
	L.lookingforgroup3	= "Присоединился к поиску группы"
	L.lookingforgroup4	= "Покинул поиск группы"
	L.world1	= "М"
	L.world2	= "Мир"
	L.world3	= "Присоединился к мировому каналу"
	L.world4	= "Покинул мировой канал"
	L.rep	= "Р"
	L.eql	= "Ур. экипировки"
	L.class	= "Класс"
	L.spec	= "Специализация"

	-- Информация
	L.fps	= "FPS"
	L.lag	= "Задержка"
	L.player	= "И"
	L.target	= "Ц"
	L.vehicle	= "Т"
	L.none	= "Нет"
	L.lootspec	= "СПЕЦ"
	L.ile = "илвл"
	L.str	= "Сил"
	L.agi	= "Лов"
	L.int	= "Инт"
	L.cri	= "Крит"
	L.has	= "Скор"
	L.mas	= "Искус"
	L.ver	= "Универ"

	L.attp	= "Силаз"
	L.spbd	= "Силаа"
	L.armp	= "Пробивание"
	L.manar	= "MP5"
	L.armor	= "Броня"
	L.dodge	= "Уклонение"
	L.parry	= "Пар."
	L.block	= "Блок"
	L.atts	= "Скорость"

	L.clearm	= "Очистить память"
	L.total	= "Всего"
	L.totalb	= "Всего, включая Blizzard"
	L.sspec	= "Сменить специализацию"
	L.nospec	= "Еще не специализирован"
	L.slspec	= "Сменить специализацию для сбора"

	-- Модули
	L.guildrepair	= "В этот раз использован ремонт гильдии"
	L.guildra	= "Осталось доступных ремонтов гильдии"
	L.selfrepair	= "Ремонт за свой счет"
	L.norepair	= "У меня нет денег на ремонт снаряжения."
	L.sellg	= "Продажа мусора"
	L.hidoroff	= "Сторона невидима или персонаж не в сети, невозможно пригласить"
	L.cutin	= "Вырезать "
	L.enytc	= "Введите имя, которое хотите изменить, оставьте пустым для восстановления оригинального имени"
	L.carti	= "Подтвердите и перезагрузите интерфейс"
	L.chr3	= "История чата"

	-- Другое
	L.buyco	= "Успешно куплен 1 предмет"
	L.buydpc	= "Ошибка покупки, изменилась цена"
	L.buyalp	= "Купить по минимальной цене"
	L.untre	= "Невозможно сбросить"
	L.hbre	= "Сброшено"
	L.hbre	= "Сброшено"
	L.ltteam	= "Покидание команды"
	L.ftayt	= "Для этого мероприятия ваша команда заполнена и будет удалена из списка"
	L.era	= "ЭРА"

	-- Настройки аддона
	L.cdscr	= "Настройки DBM, Skada.. изменены, перезагрузка интерфейса для применения изменений!"
	L.confirm	= "Подтвердить"
	L.cancel	= "Отмена"
	L.setup	= "Настройка"
	L.ritss	= "Сбросить интерфейс для сохранения настроек"

	-- Настройки CVar
	L.comlc	= "Отключить настройки во время боя"
	L.decpt	= "Обнаружен плагин сбора ошибок, отключение стандартного отображения ошибок LUA"
	L.nedtc	= "Ошибок не обнаружено. Плагин сбора включает стандартное отображение ошибок LUA"
	L.on	= "ВКЛ"
	L.off	= "ВЫКЛ"
	L.tgcb	= "Полоса заклинаний цели"
	L.comif	= "Информация о бое"
	L.teaml	= "Расположение команды"
	L.tprl	= "Расположение рейда на 20 человек"
	L.tfprl	= "Расположение рейда на 25 человек"
	L.fprl	= "Расположение рейда на 40 человек"
	L.tips	= "Подсказки"
	L.itine	= "Если есть ошибка, перезагрузите интерфейс!"
	L.reload	= "Перезагрузить интерфейс?"
	L.confirm	= "Подтвердить"
	L.cancel	= "Отмена"
	L.uhset	= "Настройки привычек использования"
	L.care	= "Осторожно!"
	L.nprd	= "Сбросить индикаторы здоровья к стандартным?"

	-- Подсказки
	L.afk	= "АФК"
	L.offl	= "Не в сети"
	L.rare	= "Редкий"
	L.raree	= "Редкий элитный"
	L.elite	= "Элитный"
	L.ghost	= "Призрак"
	L.dead	= "Мертв"
	L.targ	= "Цель"
	L.you	= "ВЫ"
	L.epicra	= "Эпохальный М+ рейтинг"
	L.dungeons	= "Подземелья"
	L.ratle	= "Уровни рейтинга"
	L.item	= "Предмет"
	L.iteml	= "ур. предмета"
	L.spell	= "Заклинание"
	L.ppu	= "Цена за единицу"

elseif (GetLocale()	== "frFR") then
	--by KharmaChaitea - KirinTor EU
	L.Default = "Par défaut"

	L.resd	= "Rechargez l'interface pour rétablir les paramètres par défaut"
	L.confirm	= "Confirmer"
	L.cancel	= "Annuler"
	L.dtools2	= "Amélioration de l'interface"
	L.captext	= "|cff00EE00Shift|r - Maintenir pour déplacer les avatars standards, orbes de sang, infos, etc.\n(Régler la barre d'action peut la désactiver)\n|cff00EE00/di|r - Ouvre rapidement l'interface de configuration\n|cff00EE00/npd|r - Restaure les paramètres par défaut des barres de vie"
	L.printh2	= "|cff00EE00/rl|r - Recharge l'interface\n|cff00EE00/di|r - Ouvre rapidement l'interface de configuration"
	L.printh	= "Instructions"

	L.aab1	= "Minuteur d'attaque"
	L.aab2	= "Minuteur d'attaque automatique d'arme"
	L.acu1	= "Barre d'action"
	L.acu2	= "Amélioration et décoration de la barre d'action"
	L.acm0	= "Conventionnel"
	L.acm1	= "Cliquer"
	L.acm2	= "Plus"
	L.acm3	= "Trois lignes"
	L.acc1	= "Bordure noire"
	L.acc2	= "Colorer la bordure des boutons d'action"
	L.acp1	= "Décoration avancée"
	L.acp2	= "Décorer le fond des boutons d'action"
	L.acr1	= "Cacher l'animation des icônes"
	L.acr2	= "Désactiver l'animation de lancement sur les nouvelles icônes (10.0)"
	L.aug1	= "Formation auto"
	L.aug2	= "Formation automatique des textes chiffrés (|cffFFFF00/1|r)"
	L.aur1	= "Réparation auto"
	L.aur2	= "Réparer automatiquement l'équipement (priorité à la guilde)"
	L.aus1	= "Vente auto"
	L.aus2	= "Vente automatique des objets gris"
	L.aua1	= "Capture auto"
	L.aua2	= "Capture automatique lors des hauts faits"
	L.bfm1	= "Déplacement des panneaux"
	L.bfm2	= "Déplacement libre des panneaux intégrés"
	L.cbb1	= "BarreSort joueur+"
	L.cbb2	= "Amélioration de la barre d'incantation du joueur"
	L.cbi1	= "Indicateur de combat"
	L.cbi2	= "Indicateur de combat de Bigfoot"
	L.cfp1	= "Amélioration du chat"
	L.cfp2	= "Améliorer et décorer la fenêtre de chat"
	L.cfbb1	= "Bouton en bas"
	L.cfbb2	= "Déplacer le bouton du chat en bas de la fenêtre"
	L.chr1	= "Historique de chat"
	L.chr2	= "Restaurer l'historique de chat de la dernière partie"
	L.ctbr1 = "Minuteur de combat"
	L.ctbr2 = "Outil de minuterie de combat et de résurrection en combat"
	L.fsl1	= "Loot rapide"
	L.fsl2	= "Accélérer la fenêtre de loot"
	L.glob1	= "Config glob."
	L.glob2	= "Config. commune pour tous les rôles. (Rechargement de l'interface requis.)"
	L.hsf1	= "|cff00FF00Shift|rDéfinir le focus"
	L.hsf2	= "Appuyez et maintenez|cffFFFF00Shift|rDéfinir le focus"
	L.ifs1	= "Infos système"
	L.ifs2	= "Vitesse de déplacement, FPS, Latence, Mémoire"
	L.ifsc1 = "Police colorée"
	L.ifsc2 = "Colorisation de la police des données"
	L.ifss1	= "Police grande taille"
	L.ifss2	= "Agrandir la police des infos système"
	L.ist1	= "Alerte interruption"
	L.ist2	= "Avertir quand une incantation est interrompue"
	L.npu1	= "Amélioration des barres de vie"
	L.npu2	= "Décoration simple des barres de vie"
	L.otb1	= "Décoration du suivi"
	L.otb2	= "Décorer le texte de suivi des quêtes (peut buguer en combat)"
	L.pnc1	= "Renommer le personnage"
	L.pnc2	= "|cff00FF00/CN/cname|r - Modifier le nom du personnage local"
	L.pnc3	= "|cff00FF00/CN|r Renom."
	L.ruu1	= "Décoration du cadre raid"
	L.ruu2	= "Améliorer les cadres raid"
	L.sfu1	= "Décoration des polices"
	L.sfu2	= "Décorer la majorité des textes du jeu"
	L.tiu1	= "Amélioration des infobulles"
	L.tiu2	= "Décorer et améliorer les infobulles souris"
	L.tiub1	= "Agrandir"
	L.tiub2	= "Agrandissement du cadre d'info-bulle"
	L.una1	= "Disparition du cadre joueur"
	L.una2	= "Faire disparaître le cadre si aucune cible pendant le combat"
	L.unc1	= "Couleurs de classe"
	L.unc2	= "Utiliser des couleurs de classe plus vives"
	L.unfn1	= "Cacher le nom"
	L.unfn2	= "Cacher le nom du joueur"
	L.unft1	= "Texture Élite"
	L.unft2	= "Cadre joueur avec texture de dragon doré"
	L.uns1	= "Agrandir cadre"
	L.uns2	= "Cadre d'avatar par défaut plus grand"
	L.unu1	= "Amélioration des cadres"
	L.unu2	= "Améliorer et décorer les cadres d'unités par défaut"
	L.vap1	= "Annonces vocales"
	L.vap2	= "Annonce vocale lors d'un gain de marque"

	L.oufd1	= "Orbe Diablo"
	L.oufd2	= "Cadre joueur façon Diablo par oUF"
	L.oufc1	= "Couleur de classe"
	L.oufc2	= "Colorer l’orbe selon la classe"
	L.dadf1	= "Décoration"
	L.dadf2	= "Matériaux décoratifs démons et anges"
	L.dhpg1	= "La bordure"
	L.dhpg2	= "Bordure autour des orbes de sang"
	L.dpet1	= "Cadre familier"
	L.dpet2	= "Cadre du familier au-dessus de l’orbe de vie"
	L.dduf1	= "Cadre par défaut"
	L.dduf2	= "Activer le cadre joueur par défaut (caché par oUF)"
	L.uisl1	= "Verrouillage échelle UI"
	L.uisl2	= "Verrouille l’échelle de l’interface (nécessite de repositionner ensuite)"
	L.daml1	= "Réglage fin des actions"
	L.daml2	= "Personnaliser et verrouiller certaines barres d’actions (peut buguer en combat)"

	L.bart 	= "Texture de barre"
	L.tipc 	= "Infobulle"
	L.tipc1	= "Suivre"
	L.tipc2	= "Ne pas suivre"
	L.tipc3	= "Suivre hors combat"
	L.sqw1	= "Délai d’incantation"
	L.sqw2	= "Délai entre les sorts"
	L.brtx	= "Version"
	L.adrl	= "Recharger"
	L.slb	= "Recommandé"
	L.resdef	= "Réinitialiser par défaut"
	L.respos	= "Réinitialiser la position"
	L.feedback	= "|cffEEFF7FQQGroup :|r974344392"
	L.print	= "Ouvrir l’interface de configuration"
	L.bloodcc	= "CONFIG"

		-- Chat
	L.say	= "S"
	L.yell	= "Y"
	L.party	= "P"
	L.guild	= "G"
	L.raid	= "R"
	L.instance	= "I"
	L.general1	= "G"
	L.general2	= "Général"
	L.general3	= "Vous n'avez pas de canal général"
	L.trade1	= "T"
	L.trade2	= "Commerce"
	L.trade3	= "Vous n'êtes pas dans le canal Commerce, rejoignez-le en capitale"
	L.lookingforgroup1	= "L"
	L.lookingforgroup2	= "RechercheGroupe"
	L.lookingforgroup3	= "Rejoint le canal RechercheGroupe"
	L.lookingforgroup4	= "Quitte le canal RechercheGroupe"
	L.world1	= "W"
	L.world2	= "Monde"
	L.world3	= "Rejoint le canal Monde"
	L.world4	= "Quitte le canal Monde"
	L.rep	= "R"
	L.eql	= "Niv. Éq."
	L.class	= "Classe"
	L.spec	= "Spé"

	-- Info
	L.fps	= "FPS"
	L.lag	= "Latence"
	L.player	= "P"
	L.target	= "T"
	L.vehicle	= "V"
	L.none	= "Aucun"
	L.lootspec	= "SPÉC"
	L.ile = "Ilvl"
	L.str	= "Str"
	L.agi	= "Agi"
	L.int	= "Int"
	L.cri	= "Cri"
	L.has	= "Has"
	L.mas	= "Mas"
	L.ver	= "Ver"

	L.attp	= "AP"
	L.spbd	= "SP"
	L.armp	= "ArPen"
	L.manar	= "Mp5"
	L.armor	= "Armure"
	L.dodge	= "Esquive"
	L.parry	= "Parade"
	L.block	= "Bloquage"
	L.atts	= "Vitesse"

	L.clearm	= "Nettoyer la mémoire"
	L.total	= "Total"
	L.totalb	= "Total (incl. Blizzard)"
	L.sspec	= "Changer de spé"
	L.nospec	= "Pas encore spécialisé"
	L.slspec	= "Changer spé de butin"

	-- Modules
	L.guildrepair	= "Réparation via la guilde effectuée"
	L.guildra	= "Réparations de guilde restantes"
	L.selfrepair	= "Réparation à vos frais"
	L.norepair	= "Vous n'avez pas assez d'argent pour réparer l'équipement."
	L.sellg	= "Vente d'objets gris"
	L.hidoroff	= "Joueur invisible ou hors ligne, invitation impossible"
	L.cutin	= "Couper "
	L.enytc	= "Entrez le nom à modifier, laissez vide pour restaurer"
	L.carti	= "Confirmer et recharger l'interface"
	L.chr3	= "Historique de chat"

	-- Autres
	L.buyco	= "Achat d’un objet réussi"
	L.buydpc	= "Échec de l'achat, prix modifié"
	L.buyalp	= "Acheter au prix le plus bas"
	L.untre	= "Impossible de réinitialiser"
	L.hbre	= "Réinitialisé"
	L.ltteam	= "Quitter l'équipe"
	L.ftayt	= "Votre groupe est complet et sera retiré de la liste"
	L.era	= "ÈRE"

	-- Configuration de l'addon
	L.cdscr	= "Paramètres modifiés pour DBM, Skada... Recharge requise !"
	L.confirm	= "Confirmer"
	L.cancel	= "Annuler"
	L.setup	= "Configurer"
	L.ritss	= "Réinitialiser l'interface pour sauvegarder les paramètres"

	-- CVars
	L.comlc	= "Désactiver les paramètres en combat"
	L.decpt	= "Plugin de collecte d'erreurs détecté, affichage des erreurs LUA désactivé"
	L.nedtc	= "Aucune erreur détectée. Plugin actif pour afficher les erreurs LUA"
	L.on	= "ON"
	L.off	= "OFF"
	L.tgcb	= "Barre d'incantation cible"
	L.comif	= "Infos de combat"
	L.teaml	= "Disposition du groupe"
	L.tprl	= "Disposition raid 20"
	L.tfprl	= "Disposition raid 25"
	L.fprl	= "Disposition raid 40"
	L.tips	= "Astuces"
	L.itine	= "En cas d’erreur, rechargez l’interface !"
	L.reload	= "Recharger l'interface ?"
	L.confirm	= "Confirmer"
	L.cancel	= "Annuler"
	L.uhset	= "Préférences d'utilisation"
	L.care	= "Attention !"
	L.nprd	= "Réinitialiser les barres de vie par défaut?"

	-- Infobulles
	L.afk	= "AFK"
	L.offl	= "Hors ligne"
	L.rare	= "Rare"
	L.raree	= "Rare élite"
	L.elite	= "Élite"
	L.ghost	= "Fantôme"
	L.dead	= "Mort"
	L.targ	= "Cible"
	L.you	= "VOUS"
	L.epicra	= "Score épique"
	L.dungeons	= "Donjons"
	L.ratle	= "Niveaux de cote"
	L.item	= "Objet"
	L.iteml	= "Niv. d’objet"
	L.spell	= "Sort"
	L.ppu	= "Prix Unitaire"
	L.diablotip = "|cffffff00Désactivez dans la liste des modules|r"

else

	L.Default = "Default"

	L.resd	= "Reload interface to restore default"
	L.confirm	= "Confirm"
	L.cancel	= "Cancel"
	L.dtools2	= "UI beautify"
	L.captext	= "|cff00EE00Shift|r down to move default avatars, dark blood cells, data information, etc\n(Adjusting the action bar can turn off the action bar)\n|cff00EE00/di|r Quickly open the settings interface\n|cff00EE00/npd|r Restore nameplates default settings"
	L.printh2	= "|cff00EE00/rl|r Reload interface\n|cff00EE00/di|r Quickly open the settings interface"
	L.printh	= "Instructions"

	L.aab1	= "Attack Timer"
	L.aab2	= "Weapon Auto Attack Timer"
	L.acu1	= "ActionBar"
	L.acu2	= "Action bar enhance and beautify"
	L.acm0	= "Precedent"
	L.acm1	= "Click"
	L.acm2	= "More"
	L.acm3	= "Three lines"
	L.acc1	= "Blackout border"
	L.acc2	= "Dye action bar button border"
	L.acp1	= "Advanced beautify"
	L.acp2	= "Beautify the background of the action bar button border"
	L.acr1	= "Hide icon animation"
	L.acr2	= "Close the newly added icon casting animation in 10.0"
	L.aug1	= "Auto formation"
	L.aug2	= "Auto formation of ciphertext(|cffFFFF00/1|r)"
	L.aur1	= "Auto repair"
	L.aur2	= "Auto repair equipment (priority given to guild repairs)"
	L.aus1	= "Auto sales"
	L.aus2	= "Autoally sell gray garbage"
	L.aua1	= "Auto screenshot"
	L.aua2	= "Obtain Auto screenshots of achievements"
	L.bfm1	= "Panel movement"
	L.bfm2	= "Free movement of builtin panel frame"
	L.cbb1	= "CastBar+"
	L.cbb2	= "Player Cast Bar Enhancement"
	L.cbi1	= "CombatIndicator"
	L.cbi2	= "CombatIndicator by Bigfoot"
	L.cfp1	= "Chat enhance"
	L.cfp2	= "Talk about beautify and enhance"
	L.cfbb1	= "Bottom button"
	L.cfbb2	= "Move the chat bar button to the bottom of the frame"
	L.chr1	= "Chat History"
	L.chr2	= "Restore Last Game's Chat History"
	L.ctbr1 = "Combat Timer"
	L.ctbr2 = "Battle Resurrection and Combat Timer Tool"
	L.fsl1	= "Quick Pick"
	L.fsl2	= "Pick frame acceleration"
	L.glob1	= "Global Config"
	L.glob2	= "Shared config for all roles. (UI reload required after change.)"
	L.hsf1	= "|cff00FF00Shift|rSet focus"
	L.hsf2	= "Press and hold|cffFFFF00Shift|rset focus"
	L.ifs1	= "Data information"
	L.ifs2	= "Movement speed, FPS, Lag, Memory"
	L.ifsc1 = "Colored Font"
	L.ifsc2 = "Data Font Coloring"
	L.ifss1	= "Large font"
	L.ifss2	= "Increase the font size of data information"
	L.ist1	= "Interrupt prompt"
	L.ist2	= "Interrupt target casting prompt"
	L.npu1	= "Nameplate enhance"
	L.npu2	= "Simple Nameplate beautify enhance"
	L.otb1	= "Tracking beautify"
	L.otb2	= "Task tracking text beautification(Possible interface behavior failure during combat)"
	L.pnc1	= "Character renaming"
	L.pnc2	= "|cff00FF00/CN/cname|r Change local player character names"
	L.pnc3	= "|cff00FF00/CN|r Rename"
	L.ruu1	= "RaidFrame beautify"
	L.ruu2	= "RaidFrame beautify"
	L.sfu1	= "Font beautify"
	L.sfu2	= "Beautify most of the text in the game"
	L.tiu1	= "Tip enhance"
	L.tiu2	= "Mouse tip beautify and enhance"
	L.tiub1	= "Enlarge"
	L.tiub2	= "Tooltip Frame Enlargement"
	L.una1	= "PlayerFrame fadeout"
	L.una2	= "A framework for gradually disappearing avatars without a target in battle"
	L.unc1	= "Class color adjustment"
	L.unc2	= "Use a bright set of professional colors"
	L.unfn1	= "Hide name"
	L.unfn2	= "Hide player name"
	L.unft1	= "Elite texture"
	L.unft2	= "Player frame made of golden dragon texture"
	L.uns1	= "Enlarge frame"
	L.uns2	= "Larger default avatar frame"
	L.unu1	= "Frame enhance"
	L.unu2	= "Default unitframe beautify enhance"
	L.vap1	= "Voice Announcements"
	L.vap2	= "Mark gain voice prompt"

	L.oufd1	= "Diablo Orb"
	L.oufd2	= "Diablo Orb PlayerFrame by oUF"
	L.oufc1	= "Class color"
	L.oufc2	= "Orb dyeing of class color"
	L.dadf1	= "Decoration"
	L.dadf2	= "Decorative materials for demons and angels"
	L.dhpg1	= "Border"
	L.dhpg2	= "The border around the blood cell"
	L.dpet1	= "Pet frame"
	L.dpet2	= "Pet frame above the orb of life"
	L.dduf1	= "Default Frame"
	L.dduf2	= "Enable default playerFrame hidden by oUF"
	L.uisl1	= "UI Scale lock"
	L.uisl2	= "Open and lock UI scale(After adjusting the UI scale, it is necessary to reset the position)"
	L.daml1	= "Actionfine-tuning"
	L.daml2	= "Customize and lock some action bars(Editing mode will report errors during combat)"

	L.bart 	= "Bar Texture"
	L.tipc 	= "Tooltip"
	L.tipc1	= "Follow"
	L.tipc2	= "Do not follow"
	L.tipc3	= "Non Combat Follow"
	L.sqw1	= "Cast delay"
	L.sqw2	= "Cast sequence delay"
	L.brtx	= "Version"
	L.adrl	= "Reload"
	L.slb	= "Recommendation"
	L.resdef	= "Restore default"
	L.respos	= "Reset position"
	L.feedback	= "|cffEEFF7FQQGroup :|r974344392"
	L.print	= "Open the settings interface"
	L.bloodcc	= "CONFIG"
	L.diablotip = "|cffffff00Disable in the addon list|r"


	--chat
	L.say	= "S"
	L.yell	= "Y"
	L.party	= "P"
	L.guild	= "G"
	L.raid	= "R"
	L.instance	= "I"
	L.general1	= "G"
	L.general2	= "General"
	L.general3	= "You don't have a general channel"
	L.trade1	= "T"
	L.trade2	= "Trade"
	L.trade3	= "You are not on the trading channel, please join in the main city"
	L.lookingforgroup1	= "L"
	L.lookingforgroup2	= "LookingForGroup"
	L.lookingforgroup3	= "Joined LookingForGroup"
	L.lookingforgroup4	= "Leaving LookingForGroup"
	L.world1	= "W"
	L.world2	= "world"
	L.world3	= "Joined World Channel"
	L.world4	= "Leaving World Channel"
	L.rep	= "R"
	L.eql	= "Eq level"
	L.class	= "Class"
	L.spec	= "Spec"


	--info
	L.fps	= "FPS"
	L.lag	= "Lag"
	L.player	= "P"
	L.target	= "T"
	L.vehicle	= "V"
	L.none	= "Nil"
	L.lootspec	= "SPEC"
	L.ile = "Ilvl"
	L.str	= "Str"
	L.agi	= "Agi"
	L.int	= "Int"
	L.cri	= "Cri"
	L.has	= "Has"
	L.mas	= "Mas"
	L.ver	= "Ver"

	L.attp	= "AP"
	L.spbd	= "SP"
	L.armp	= "ArPen"
	L.manar	= "Mp5"
	L.armor	= "Armor"
	L.dodge	= "Dodge"
	L.parry	= "Parry"
	L.block	= "Block"
	L.atts	= "ASpeed"

	L.clearm	= "Clean up memory"
	L.total	= "Total"
	L.totalb	= "Total incl.Blizzard"
	L.sspec	= "Switch Spec"
	L.nospec	= "Not specialized yet"
	L.slspec	= "Switch Pick Spec"


	--modules
	L.guildrepair	= "This time using guild repair"
	L.guildra	= "Remaining guild repairs available"
	L.selfrepair	= "Self funded repair"
	L.norepair	= "I don't have money to repair equipment."
	L.sellg	= "Selling garbage"
	L.hidoroff	= "The other party is invisible or has no character online, unable to invite"
	L.cutin	= "Cut "
	L.enytc	= "Enter the name you want to change, do not enter to restore the original name"
	L.carti	= "Confirm and reload the interface"
	L.chr3	= "Chat History"


	--other
	L.buyco	= "Successfully purchased 1 item"
	L.buydpc	= "Purchase failure, price change"
	L.buyalp	= "Buy one at the lowest price"
	L.untre	= "Unable to reset"
	L.hbre	= "Has been reset"
	L.hbre	= "Has been reset"
	L.ltteam	= "Leaving the team"
	L.ftayt	= "For this activity, your team is full and will be removed from the list"
	L.era	= "ERA"


	--setaddon
	L.cdscr	= "DBM, Skada.. Settings have been changed, reloading interface application changes!"
	L.confirm	= "Confirm"
	L.cancel	= "Cancel"
	L.setup	= "Set up"
	L.ritss	= "Reset interface to save settings"


	--setcvar
	L.comlc	= "Disable settings during battles"
	L.decpt	= "Detected error collection plugin turning off default LUA error display"
	L.nedtc	= "No error detected. The collection plugin opens the default LUA error display"
	L.on	= "ON"
	L.off	= "OFF"
	L.tgcb	= "Target casting bar"
	L.comif	= "Combat information"
	L.teaml	= "Team Layout"
	L.tprl	= "20 person raid layout"
	L.tfprl	= "25 person raid layout"
	L.fprl	= "40 person raid layout"
	L.tips	= "Tips"
	L.itine	= "If there is an error, please reload the interface!"
	L.reload	= "Reload UI?"
	L.confirm	= "Confirm"
	L.cancel	= "Cancel"
	L.uhset	= "Usage habits settings"
	L.care	= "Careful!"
	L.nprd	= "Reset Nameplates to Default?"


	--tooltip
	L.afk	= "AFK"
	L.offl	= "Offline"
	L.rare	= "Rare"
	L.raree	= "Rareelite"
	L.elite	= "Elite"
	L.ghost	= "Ghost"
	L.dead	= "Dead"
	L.targ	= "Target"
	L.you	= "YOU"
	L.epicra	= "Epic Rating"
	L.dungeons	= "Dungeons"
	L.ratle	= "Rating Levels"
	L.item	= "Item"
	L.iteml	= "Item Level"
	L.spell	= "Spell"
	L.ppu	= "Unit Price"

end